version: '3.6'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - integrador_backend

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - integrador_backend

  productos:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/products?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - integrador_backend
    volumes:
      - ./.env:/.env
      

  imagenes:
    build:
      context: ../images-microservice/
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/products?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - integrador_backend
    volumes:
      - ./.env:/.env
      - ../images:/app/images  

networks:
  integrador_backend:
    driver: bridge
    
