name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Build and test
        run: |
          go build -o main
          go test ./...

      - name: Deploy to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t products-microservice:latest .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u diegogmrn --password-stdin
          docker push docker.io/ecommerce-proyecto-integrador/products-microservice:latest
      - name: Debug secrets
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
