name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1

      - name: Build and test
        run: |
          go build -o main
          go test ./...

      - name: Deploy to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker build -t products-microservice:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_PASSWORD }} 
          docker push products-microservice:latest 
      